### ISSUE TITLE
Rotation vector csv output issue

### ISSUE THREAD

**Issue by gillesmeyhi** [Foxpace/SensorBox#12]
Hi,

When I read the csv output of the rotation vector sensor I get something very strange. It looks like it is only taking samples at sporadic times. Do you know what the issue can be?

Here is an image:

![image](https://github.com/Foxpace/SensorBox/assets/58083459/2d50318f-8bd8-4e1a-b5e8-890ecdbfa569)

**Comment by Foxpace** [comment]
hi
couple of questions:
1. What kind of device is used? 
2. Do you have some battery saving turned on? I recommend visiting https://dontkillmyapp.com/ and trying to add app to whitelist. Or go to settings of the app and in "Android settings" you can permit the app to ignore battery settings. (Both solution can be ignored by the Android in dependence of the vendor)
3. Does it behave the same way on live preview on the sensor?

In my opinion the device just goes to sleep and does not send out updated sample and updates it sporadically / never. It is not fault of the app, but battery saving measures taken on your device most probably. To go around such restriction is just to keep the device screen on - this forces the Android to process new samples during the process. 

For more details, I recommend reading my article: [Medium article](https://medium.com/@tomas-repcik/why-do-you-not-get-your-notification-alarm-or-updated-status-on-android-a3a3e1d070ec)
