### ISSUE TITLE
Setting sampling rate

### ISSUE THREAD

**Issue by svenu96** [Foxpace/SensorBox#8]
I cant set the sampling rate in the app. Is there a way to do that?

**Comment by Foxpace** [comment]
Hello,

the Android platform does not support sampling frequencies as you might think.

The Android takes in only number of ms, till which the system should deliver thr sample. But in the end the app receives sample from the system, when the system decides.

Example, lets set max delay for 100ms, so every sample will be delivered in 100ms. If it is in 50ms, 25ms or 1ms, it depends on Android. It is not even obliged to deliver it at all - this value is taken as preffered value and Android can just ignore it. 

Why? Other processes, battery settings, low battery, low resources,...

That is why, sampling frequency can vary every time, you take measurement.  It is not constant. 

You can set this option in menu - > advanced - > pick sensors - > pick measurement type - > max delay

More granularity in the shown options there would be useless as Android will do its own thing still. 

I recommend to set it to 0ms, take all the data, what you can and if need to, resample them in required sampling frequency. The purpose of the app is to record raw data, not artificial - no such option in the app exists. 

If other app has such option, they interpolate samples / resample them and the data are not in raw form. 

Hopefully, you will find this helpful.
